SELECT * FROM producto;
SELECT nombre, precio FROM producto;
SHOW COLUMNS FROM producto;
SELECT nombre, precio, precio* 1.08 FROM producto;
SELECT nombre as nombre_Producto, precio as Euros, precio *1.08 as Dolares_Americanos FROM producto;
SELECT upper(nombre), precio FROM producto;
SELECT lower(nombre), precio FROM producto;
SELECT nombre FROM fabricante;
SELECT nombre, CONCAT(substring(upper(nombre),1,2), substring(LOWER(nombre),3)) AS nombre FROM producto;
SELECT nombre, round(precio) precio FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT distinct(codigo_fabricante) FROM producto;
SELECT* FROM fabricante ORDER BY nombre ASC;
SELECT* FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC,nombre DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3,3;
SELECT nombre, precio FROM producto  ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto  ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto. nombre, precio, fabricante.nombre AS nombre_fabricante FROM producto, fabricante;
-- UNIVERSIDAD;
SELECT  apellido1, apellido2, nombre FROM persona ORDER BY apellido1 ASC ;
SELECT nombre, apellido1, apellido2 FROM persona WHERE telefono IS NULL;
SELECT nombre, apellido1, apellido2 FROM persona WHERE fecha_nacimiento BETWEEN "1999-01-01" AND "1999-12-31";
SELECT * FROM persona WHERE telefono IS NULL AND tipo = "profesor" AND nif LIKE "%k";
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT pe.apellido1, pe.apellido2, pe.nombre, de.nombre FROM persona pe JOIN profesor pr ON  pe.id = pr.id_profesor JOIN departamento de ON pr.id_departamento = de.id ORDER BY pe.apellido1, pe.apellido2, pe.nombre;
SELECT a.nombre, ce.anyo_inicio, ce.anyo_fin FROM persona pe JOIN  alumno_se_matricula_asignatura asma ON pe.id = asma.id_alumno JOIN asignatura a ON  a.id = asma.id_asignatura JOIN curso_escolar ce ON ce.id = asma.id_curso_escolar WHERE nif= '26902806M';
SELECT de.nombre "Nombre Departamento", asi.nombre "Asignatura" FROM departamento de JOIN profesor pro ON de.id = pro.id_departamento JOIN asignatura asi ON pro.id_profesor = asi.id_profesor JOIN grado g ON asi.id_grado = g.id WHERE g.id = 4;
SELECT pe.apellido1, pe.apellido2, pe.nombre, ce.anyo_inicio, ce.anyo_fin FROM universidad.alumno_se_matricula_asignatura asma JOIN curso_escolar ce ON asma.id_curso_escolar = ce.id JOIN persona pe ON asma.id_alumno = pe.id  WHERE ce.id = 5;
SELECT de.nombre Departamento, pe.apellido1 Apellido, pe.apellido2 "Segundo apellido", pe.nombre Nombre FROM persona pe JOIN profesor pro ON pe.id = pro.id_profesor RIGHT JOIN departamento de ON pro.id_departamento = de.id ORDER BY de.nombre DESC, pe.apellido1 DESC, pe.apellido2 DESC, pe.nombre DESC;
SELECT * FROM profesor pro LEFT JOIN departamento de ON pro.id_profesor = de.id WHERE de.id IS NULL;
SELECT de.nombre FROM persona pe JOIN profesor pro ON pe.id = pro.id_profesor RIGHT JOIN departamento de ON pro.id_departamento = de.id WHERE pro.id_departamento is null;
SELECT * FROM persona pe RIGHT JOIN profesor pro ON pe.id = pro.id_profesor LEFT JOIN asignatura a ON pro.id_profesor = a.id_profesor WHERE a.id IS NULL;
SELECT a.nombre FROM persona pe RIGHT JOIN profesor pro ON pe.id = pro.id_profesor RIGHT JOIN asignatura a ON pro.id_profesor = a.id_profesor WHERE pro.id_profesor IS NULL;
SELECT DISTINCT de.nombre FROM departamento de LEFT JOIN profesor pro ON de.id = pro.id_departamento LEFT JOIN asignatura a ON pro.id_profesor = a.id_profesor LEFT JOIN curso_escolar ce ON a.curso = ce.id WHERE ce.id IS NULL ;
 -- RESUM
SELECT COUNT(tipo) 'alumnos total'FROM persona WHERE tipo = 'alumno';
SELECT COUNT(fecha_nacimiento) 'fecha_nacimiento'FROM persona WHERE fecha_nacimiento LIKE '1999%';
SELECT de.nombre, count(pro.id_departamento) Profesores FROM departamento de LEFT JOIN profesor pro ON de.id = pro.id_departamento WHERE pro.id_departamento IS NOT NULL GROUP BY pro.id_departamento ORDER BY 2 DESC;
SELECT de.nombre, count(pro.id_departamento) Profesores FROM departamento de LEFT JOIN profesor pro ON de.id = pro.id_departamento WHERE pro.id_departamento IS NOT NULL GROUP BY pro.id_departamento ORDER BY 2 DESC;
SELECT de.nombre Departamento, COUNT(pro.id_departamento) 'Total Profesores' FROM departamento de LEFT JOIN profesor pro ON de.id = pro.id_departamento GROUP BY de.nombre ORDER BY 2 DESC ;
