-- MySQL Script generated by MySQL Workbench
-- Tue Feb  7 19:12:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Client` (
  `id_Client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `primer_cognom` VARCHAR(45) NOT NULL,
  `segon_cognom` VARCHAR(45) NOT NULL,
  `adreça` VARCHAR(45) NOT NULL,
  `codi_postal` INT NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefon` INT(11) NOT NULL,
  PRIMARY KEY (`id_Client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Botiga` (
  `idBotiga` INT NOT NULL AUTO_INCREMENT,
  `adreça` TEXT NOT NULL,
  `codi_postal` INT(5) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBotiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda` (
  `id_Comanda` INT NOT NULL AUTO_INCREMENT,
  `comanda_hora` DATETIME NOT NULL,
  `tipus_comanda` VARCHAR(45) NOT NULL,
  `productes` INT NOT NULL,
  `preu` DECIMAL(5) NOT NULL,
  `Botiga_idBotiga` INT NOT NULL,
  `Client_id_Client` INT NOT NULL,
  `cantidad_productes` INT NOT NULL,
  PRIMARY KEY (`id_Comanda`, `Client_id_Client`),
  INDEX `fk_Comanda_Botiga_idx` (`Botiga_idBotiga` ASC) VISIBLE,
  INDEX `fk_Comanda_Client1_idx` (`Client_id_Client` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda_Botiga`
    FOREIGN KEY (`Botiga_idBotiga`)
    REFERENCES `Pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comanda_Client1`
    FOREIGN KEY (`Client_id_Client`)
    REFERENCES `Pizzeria`.`Client` (`id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Productes` (
  `idProductes` INT NOT NULL AUTO_INCREMENT,
  `Comanda_id_Comanda` INT NOT NULL,
  `Comanda_Client_id_Client` INT NOT NULL,
  PRIMARY KEY (`idProductes`),
  INDEX `fk_Productes_Comanda1_idx` (`Comanda_id_Comanda` ASC, `Comanda_Client_id_Client` ASC) VISIBLE,
  CONSTRAINT `fk_Productes_Comanda1`
    FOREIGN KEY (`Comanda_id_Comanda` , `Comanda_Client_id_Client`)
    REFERENCES `Pizzeria`.`Comanda` (`id_Comanda` , `Client_id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Pizza` (
  `idPizza` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `preu` VARCHAR(45) NOT NULL,
  `imatge` VARCHAR(45) NOT NULL,
  `Productes_idProductes` INT NOT NULL,
  PRIMARY KEY (`idPizza`),
  INDEX `fk_Pizza_Productes1_idx` (`Productes_idProductes` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_Productes1`
    FOREIGN KEY (`Productes_idProductes`)
    REFERENCES `Pizzeria`.`Productes` (`idProductes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Hamburguesa` (
  `idhamburguesa` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `preu` INT NOT NULL,
  `imatge` VARCHAR(45) NOT NULL,
  `Productes_idProductes` INT NOT NULL,
  PRIMARY KEY (`idhamburguesa`),
  INDEX `fk_Hamburguesa_Productes1_idx` (`Productes_idProductes` ASC) VISIBLE,
  CONSTRAINT `fk_Hamburguesa_Productes1`
    FOREIGN KEY (`Productes_idProductes`)
    REFERENCES `Pizzeria`.`Productes` (`idProductes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Beguda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Beguda` (
  `idBeguda` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `preu` INT NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `Productes_idProductes` INT NOT NULL,
  PRIMARY KEY (`idBeguda`),
  INDEX `fk_Beguda_Productes1_idx` (`Productes_idProductes` ASC) VISIBLE,
  CONSTRAINT `fk_Beguda_Productes1`
    FOREIGN KEY (`Productes_idProductes`)
    REFERENCES `Pizzeria`.`Productes` (`idProductes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Repartidor` (
  `idRepartidor` INT NOT NULL AUTO_INCREMENT,
  `entraga` DATETIME NOT NULL,
  PRIMARY KEY (`idRepartidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Empleats` (
  `idEmpleats` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom1` VARCHAR(45) NOT NULL,
  `cognom2` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(10) NOT NULL,
  `telefon` INT(9) NOT NULL,
  `Botiga_idBotiga` INT NOT NULL,
  `Repartidor_idRepartidor` INT NOT NULL,
  `tipus_empleat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleats`, `Botiga_idBotiga`),
  INDEX `fk_Empleats_Botiga1_idx` (`Botiga_idBotiga` ASC) VISIBLE,
  INDEX `fk_Empleats_Repartidor1_idx` (`Repartidor_idRepartidor` ASC) VISIBLE,
  CONSTRAINT `fk_Empleats_Botiga1`
    FOREIGN KEY (`Botiga_idBotiga`)
    REFERENCES `Pizzeria`.`Botiga` (`idBotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleats_Repartidor1`
    FOREIGN KEY (`Repartidor_idRepartidor`)
    REFERENCES `Pizzeria`.`Repartidor` (`idRepartidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
